---
# control
control:
  depth: '3'
  loss_mode: 'exact-physics'
  loss_commit: '0-0'
# data
data_name: Turb
# model
model_name: vqvae
# experiment
num_workers: 0
init_seed: 0
num_experiments: 1
log_interval: 0.25
device: cuda
world_size: 1
resume_mode: 0
# other
fig_format: png
